/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ide;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathIdeSetup /* implements MathStandaloneSetup  */{
  @Override
  public Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules2 is undefined"
      + "\nMathRuntimeModule cannot be resolved."
      + "\ncreateInjector cannot be resolved"
      + "\nmixin cannot be resolved");
  }
}
